smoke-test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -422,50 +422,52 @@ jobs:
       - revert_migrations:
           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"    
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-      # - image: cimg/base:stable
-      # - image: amazon/aws-cli
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-              # curl -fsSL https://deb.nodesource.com/setup_13.x | bash - && yum -y install nodejs tar gzip
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-            # BACKEND_IP=$(aws ec2 describe-instances \
-            #   --filters "Name=tag:Name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            #   --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            #   --output text)
-            # export API_URL="http://${BACKEND_IP}:3030"
-            # if curl -s $API_URL/api/status | grep "ok"
-            # then 
-            #   exit 0
-            # else
-            #   exit 1 
-            # fi 
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      #- image: cimg/base:stable
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            #curl -fsSL https://deb.nodesource.com/setup_13.x | bash - && yum -y install nodejs tar gzip
+            curl -fsSL https://rpm.nodesource.com/setup_13.x | bash - && yum -y install nodejs tar gzip
+      - run:
+          name: backend smoke test.
+          command: |
+            # your code here
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            if curl -s $API_URL/api/status | grep "ok"
+            then 
+              exit 0
+            else
+              exit 1 
+            fi 
             
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-              # URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
-              # if curl -s ${URL} | grep "Welcome"
-              # then
-              #   return 0
-              # else
-              #   return 1
-              # fi
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+              if curl -s ${URL} | grep "Welcome"
+              then
+                return 0
+              else
+                return 1
+              fi
+      # - run:
+      #     name: Frontend smoke test.
+      #     command: |
+      #       # your code here
+
+      # Here's where you will add some code to rollback on failure  
 
 #   cloudfront-update:
 #     docker:
@@ -528,8 +530,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
